# Generated by Django 5.1.2 on 2024-10-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailySummary',
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='main',
            field=models.CharField(max_length=100),
        ),
    ]
